server {
    listen 80;

    server_name site2.local;

    return 301 https://site2.local$request_uri;
}

server {
    listen 443 ssl;

    server_name site2.local;

    root /var/www/site2;

    index index.html;

    ssl_certificate /etc/nginx/ssl/site2.local.crt;
    ssl_certificate_key /etc/nginx/ssl/site2.local.key;

    location / {
    }

    error_page 404 /404.html;
}
